# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/mainwindow.ui',
# licensing of 'designer/mainwindow.ui' applies.
#
# Created: Mon Oct 28 16:27:03 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1231, 819)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 3, 0, 1, 1)
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.CHZ_VDD = QtWidgets.QLCDNumber(self.groupBox_4)
        self.CHZ_VDD.setMinimumSize(QtCore.QSize(0, 32))
        self.CHZ_VDD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHZ_VDD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHZ_VDD.setObjectName("CHZ_VDD")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.CHZ_VDD)
        self.CHZ_M = QtWidgets.QLCDNumber(self.groupBox_4)
        self.CHZ_M.setMinimumSize(QtCore.QSize(0, 32))
        self.CHZ_M.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHZ_M.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHZ_M.setObjectName("CHZ_M")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.CHZ_M)
        self.CHZ_BIAS = QtWidgets.QLCDNumber(self.groupBox_4)
        self.CHZ_BIAS.setMinimumSize(QtCore.QSize(0, 32))
        self.CHZ_BIAS.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHZ_BIAS.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHZ_BIAS.setObjectName("CHZ_BIAS")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.CHZ_BIAS)
        self.CHZ_S = QtWidgets.QLCDNumber(self.groupBox_4)
        self.CHZ_S.setMinimumSize(QtCore.QSize(0, 32))
        self.CHZ_S.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHZ_S.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHZ_S.setObjectName("CHZ_S")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.CHZ_S)
        self.CHZ_RTN = QtWidgets.QLCDNumber(self.groupBox_4)
        self.CHZ_RTN.setMinimumSize(QtCore.QSize(0, 32))
        self.CHZ_RTN.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHZ_RTN.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHZ_RTN.setObjectName("CHZ_RTN")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.CHZ_RTN)
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_28)
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_29)
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_30)
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_22)
        self.gridLayout_5.addLayout(self.formLayout_8, 1, 1, 5, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_4)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 0, 1, 1, 1)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.CHZ_VDD_ADC = QtWidgets.QLCDNumber(self.groupBox_4)
        self.CHZ_VDD_ADC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHZ_VDD_ADC.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHZ_VDD_ADC.setObjectName("CHZ_VDD_ADC")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.CHZ_VDD_ADC)
        self.CHZ_M_ADC = QtWidgets.QLCDNumber(self.groupBox_4)
        self.CHZ_M_ADC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHZ_M_ADC.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHZ_M_ADC.setObjectName("CHZ_M_ADC")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.CHZ_M_ADC)
        self.CHZ_BIAS_ADC = QtWidgets.QLCDNumber(self.groupBox_4)
        self.CHZ_BIAS_ADC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHZ_BIAS_ADC.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CHZ_BIAS_ADC.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHZ_BIAS_ADC.setObjectName("CHZ_BIAS_ADC")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.CHZ_BIAS_ADC)
        self.CHZ_S_ADC = QtWidgets.QLCDNumber(self.groupBox_4)
        self.CHZ_S_ADC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHZ_S_ADC.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CHZ_S_ADC.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHZ_S_ADC.setObjectName("CHZ_S_ADC")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.CHZ_S_ADC)
        self.CHZ_RTN_ADC = QtWidgets.QLCDNumber(self.groupBox_4)
        self.CHZ_RTN_ADC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHZ_RTN_ADC.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CHZ_RTN_ADC.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHZ_RTN_ADC.setObjectName("CHZ_RTN_ADC")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.CHZ_RTN_ADC)
        self.label_46 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_46)
        self.label_47 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_47)
        self.label_48 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_48)
        self.label_49 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_49)
        self.label_50 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_50)
        self.gridLayout_5.addLayout(self.formLayout_9, 1, 2, 5, 1)
        self.label_51 = QtWidgets.QLabel(self.groupBox_4)
        self.label_51.setObjectName("label_51")
        self.gridLayout_5.addWidget(self.label_51, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 4, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 5, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 3, 0, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.CHY_VDD_ADC = QtWidgets.QLCDNumber(self.groupBox_5)
        self.CHY_VDD_ADC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHY_VDD_ADC.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHY_VDD_ADC.setObjectName("CHY_VDD_ADC")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.CHY_VDD_ADC)
        self.label_38 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_38)
        self.CHY_M_ADC = QtWidgets.QLCDNumber(self.groupBox_5)
        self.CHY_M_ADC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHY_M_ADC.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHY_M_ADC.setObjectName("CHY_M_ADC")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.CHY_M_ADC)
        self.label_39 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_39)
        self.CHY_BIAS_ADC = QtWidgets.QLCDNumber(self.groupBox_5)
        self.CHY_BIAS_ADC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHY_BIAS_ADC.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHY_BIAS_ADC.setObjectName("CHY_BIAS_ADC")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.CHY_BIAS_ADC)
        self.label_40 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_40)
        self.CHY_S_ADC = QtWidgets.QLCDNumber(self.groupBox_5)
        self.CHY_S_ADC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHY_S_ADC.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHY_S_ADC.setObjectName("CHY_S_ADC")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.CHY_S_ADC)
        self.label_41 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_41)
        self.CHY_RTN_ADC = QtWidgets.QLCDNumber(self.groupBox_5)
        self.CHY_RTN_ADC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHY_RTN_ADC.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHY_RTN_ADC.setObjectName("CHY_RTN_ADC")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.CHY_RTN_ADC)
        self.label_42 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_42)
        self.gridLayout_6.addLayout(self.formLayout_3, 1, 4, 5, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.CHY_VDD = QtWidgets.QLCDNumber(self.groupBox_5)
        self.CHY_VDD.setMinimumSize(QtCore.QSize(0, 32))
        self.CHY_VDD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHY_VDD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHY_VDD.setObjectName("CHY_VDD")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.CHY_VDD)
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_31)
        self.CHY_M = QtWidgets.QLCDNumber(self.groupBox_5)
        self.CHY_M.setMinimumSize(QtCore.QSize(0, 32))
        self.CHY_M.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHY_M.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHY_M.setObjectName("CHY_M")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.CHY_M)
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_32)
        self.CHY_BIAS = QtWidgets.QLCDNumber(self.groupBox_5)
        self.CHY_BIAS.setMinimumSize(QtCore.QSize(0, 32))
        self.CHY_BIAS.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHY_BIAS.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHY_BIAS.setObjectName("CHY_BIAS")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.CHY_BIAS)
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_33)
        self.CHY_S = QtWidgets.QLCDNumber(self.groupBox_5)
        self.CHY_S.setMinimumSize(QtCore.QSize(0, 32))
        self.CHY_S.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHY_S.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHY_S.setObjectName("CHY_S")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.CHY_S)
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_23)
        self.CHY_RTN = QtWidgets.QLCDNumber(self.groupBox_5)
        self.CHY_RTN.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHY_RTN.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHY_RTN.setObjectName("CHY_RTN")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.CHY_RTN)
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_24)
        self.gridLayout_6.addLayout(self.formLayout_2, 1, 3, 5, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_5)
        self.label_44.setObjectName("label_44")
        self.gridLayout_6.addWidget(self.label_44, 0, 4, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_5)
        self.label_43.setObjectName("label_43")
        self.gridLayout_6.addWidget(self.label_43, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setWeight(75)
        font.setBold(True)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 0, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_6)
        self.label_34.setObjectName("label_34")
        self.gridLayout_7.addWidget(self.label_34, 6, 0, 1, 1)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.CHX_VDD_ADC = QtWidgets.QLCDNumber(self.groupBox_6)
        font = QtGui.QFont()
        self.CHX_VDD_ADC.setFont(font)
        self.CHX_VDD_ADC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHX_VDD_ADC.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHX_VDD_ADC.setObjectName("CHX_VDD_ADC")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.CHX_VDD_ADC)
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.CHX_M_ADC = QtWidgets.QLCDNumber(self.groupBox_6)
        self.CHX_M_ADC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHX_M_ADC.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHX_M_ADC.setObjectName("CHX_M_ADC")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.CHX_M_ADC)
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.CHX_BIAS_ADC = QtWidgets.QLCDNumber(self.groupBox_6)
        self.CHX_BIAS_ADC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHX_BIAS_ADC.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHX_BIAS_ADC.setObjectName("CHX_BIAS_ADC")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.CHX_BIAS_ADC)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.CHX_S_ADC = QtWidgets.QLCDNumber(self.groupBox_6)
        self.CHX_S_ADC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHX_S_ADC.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHX_S_ADC.setObjectName("CHX_S_ADC")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.CHX_S_ADC)
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.CHX_RTN_ADC = QtWidgets.QLCDNumber(self.groupBox_6)
        self.CHX_RTN_ADC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHX_RTN_ADC.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHX_RTN_ADC.setObjectName("CHX_RTN_ADC")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.CHX_RTN_ADC)
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.gridLayout_7.addLayout(self.formLayout_4, 2, 2, 5, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 5, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_6)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 1, 2, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.CHX_VDD = QtWidgets.QLCDNumber(self.groupBox_6)
        self.CHX_VDD.setMinimumSize(QtCore.QSize(0, 32))
        self.CHX_VDD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHX_VDD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHX_VDD.setObjectName("CHX_VDD")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.CHX_VDD)
        self.label_25 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_25)
        self.CHX_M = QtWidgets.QLCDNumber(self.groupBox_6)
        self.CHX_M.setMinimumSize(QtCore.QSize(0, 32))
        self.CHX_M.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHX_M.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHX_M.setObjectName("CHX_M")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.CHX_M)
        self.label_26 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_26)
        self.CHX_BIAS = QtWidgets.QLCDNumber(self.groupBox_6)
        self.CHX_BIAS.setMinimumSize(QtCore.QSize(0, 32))
        self.CHX_BIAS.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHX_BIAS.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHX_BIAS.setObjectName("CHX_BIAS")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.CHX_BIAS)
        self.label_27 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_27)
        self.CHX_S = QtWidgets.QLCDNumber(self.groupBox_6)
        self.CHX_S.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.CHX_S.setFont(font)
        self.CHX_S.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHX_S.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHX_S.setObjectName("CHX_S")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.CHX_S)
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_19)
        self.CHX_RTN = QtWidgets.QLCDNumber(self.groupBox_6)
        self.CHX_RTN.setEnabled(True)
        self.CHX_RTN.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CHX_RTN.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CHX_RTN.setObjectName("CHX_RTN")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.CHX_RTN)
        self.label_35 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_35)
        self.gridLayout_7.addLayout(self.formLayout, 2, 1, 5, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_6)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 2, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.asicSN = QtWidgets.QLineEdit(self.groupBox_2)
        self.asicSN.setObjectName("asicSN")
        self.gridLayout_3.addWidget(self.asicSN, 1, 4, 1, 1)
        self.notes = QtWidgets.QTextEdit(self.groupBox_2)
        self.notes.setObjectName("notes")
        self.gridLayout_3.addWidget(self.notes, 0, 1, 1, 5)
        self.power_button = QtWidgets.QPushButton(self.groupBox_2)
        self.power_button.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.power_button.setFont(font)
        self.power_button.setObjectName("power_button")
        self.gridLayout_3.addWidget(self.power_button, 2, 5, 1, 1)
        self.Launch_Measurements = QtWidgets.QPushButton(self.groupBox_2)
        self.Launch_Measurements.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.Launch_Measurements.setFont(font)
        self.Launch_Measurements.setObjectName("Launch_Measurements")
        self.gridLayout_3.addWidget(self.Launch_Measurements, 1, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 2, 1, 1)
        self.notes_label = QtWidgets.QLabel(self.groupBox_2)
        self.notes_label.setObjectName("notes_label")
        self.gridLayout_3.addWidget(self.notes_label, 0, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.groupBox_2)
        self.label_52.setObjectName("label_52")
        self.gridLayout_3.addWidget(self.label_52, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1231, 29))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuSettings.addAction(self.actionSettings)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Hello", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Voltages", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "Asic channel Z", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "VDD", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "M", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "RTN", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "S", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "BIAS", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_45.setText(QtWidgets.QApplication.translate("MainWindow", "Arduino", None, -1))
        self.label_46.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_47.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_48.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_49.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_50.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_51.setText(QtWidgets.QApplication.translate("MainWindow", "ADC 12bits", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "Asic channel Y", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "M", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "RTN", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "VDD", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "S", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "BIAS", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_42.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_44.setText(QtWidgets.QApplication.translate("MainWindow", "ADC 12bits", None, -1))
        self.label_43.setText(QtWidgets.QApplication.translate("MainWindow", "Arduino", None, -1))
        self.groupBox_6.setTitle(QtWidgets.QApplication.translate("MainWindow", "Asic channel X", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "M", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "BIAS", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "RTN", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "S", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "VDD", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("MainWindow", "ADC 12bits", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("MainWindow", "Arduino", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Measurements", None, -1))
        self.power_button.setText(QtWidgets.QApplication.translate("MainWindow", "Turn ON", None, -1))
        self.Launch_Measurements.setText(QtWidgets.QApplication.translate("MainWindow", "Launch measurements", None, -1))
        self.notes_label.setText(QtWidgets.QApplication.translate("MainWindow", "Notes, radiation level...:", None, -1))
        self.label_52.setText(QtWidgets.QApplication.translate("MainWindow", "JUICEMagIC SN_", None, -1))
        self.menuSettings.setTitle(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))
        self.actionSettings.setText(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))

from . import resources_rc
