# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/settings.ui',
# licensing of 'designer/settings.ui' applies.
#
# Created: Wed Nov 20 16:23:43 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(782, 483)
        self.gridLayout = QtWidgets.QGridLayout(Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Settings)
        self.tabWidget.setObjectName("tabWidget")
        self.General = QtWidgets.QWidget()
        self.General.setObjectName("General")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.General)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_6 = QtWidgets.QGroupBox(self.General)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setObjectName("label_15")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.global_workdir = QtWidgets.QLineEdit(self.groupBox_6)
        self.global_workdir.setObjectName("global_workdir")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.global_workdir)
        self.verticalLayout_7.addLayout(self.formLayout_6)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.General)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.mail_password = QtWidgets.QLineEdit(self.groupBox_5)
        self.mail_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.mail_password.setObjectName("mail_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.mail_password)
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.mail_login = QtWidgets.QLineEdit(self.groupBox_5)
        self.mail_login.setObjectName("mail_login")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mail_login)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.mail_server = QtWidgets.QLineEdit(self.groupBox_5)
        self.mail_server.setObjectName("mail_server")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mail_server)
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.mail_recipients = QtWidgets.QLineEdit(self.groupBox_5)
        self.mail_recipients.setObjectName("mail_recipients")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.mail_recipients)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.General, "")
        self.Measurements = QtWidgets.QWidget()
        self.Measurements.setObjectName("Measurements")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Measurements)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Measurements)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.stf_amplitude = QtWidgets.QLineEdit(self.groupBox_3)
        self.stf_amplitude.setObjectName("stf_amplitude")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stf_amplitude)
        self.stf_steps = QtWidgets.QLineEdit(self.groupBox_3)
        self.stf_steps.setObjectName("stf_steps")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stf_steps)
        self.verticalLayout_2.addLayout(self.formLayout_4)
        self.gridLayout_3.addWidget(self.groupBox_3, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Measurements)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.dtf_start_freq_exp = QtWidgets.QLineEdit(self.groupBox_2)
        self.dtf_start_freq_exp.setObjectName("dtf_start_freq_exp")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dtf_start_freq_exp)
        self.dtf_stop_freq_exp = QtWidgets.QLineEdit(self.groupBox_2)
        self.dtf_stop_freq_exp.setObjectName("dtf_stop_freq_exp")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dtf_stop_freq_exp)
        self.dtf_freq_points = QtWidgets.QLineEdit(self.groupBox_2)
        self.dtf_freq_points.setObjectName("dtf_freq_points")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dtf_freq_points)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.Measurements)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.psd_snapshots_count = QtWidgets.QLineEdit(self.groupBox)
        self.psd_snapshots_count.setObjectName("psd_snapshots_count")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.psd_snapshots_count)
        self.psd_sampling_freq = QtWidgets.QLineEdit(self.groupBox)
        self.psd_sampling_freq.setObjectName("psd_sampling_freq")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.psd_sampling_freq)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.Measurements)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.asic_chx_disco = QtWidgets.QLineEdit(self.groupBox_4)
        self.asic_chx_disco.setObjectName("asic_chx_disco")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.asic_chx_disco)
        self.asic_chy_disco = QtWidgets.QLineEdit(self.groupBox_4)
        self.asic_chy_disco.setObjectName("asic_chy_disco")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.asic_chy_disco)
        self.asic_chz_disco = QtWidgets.QLineEdit(self.groupBox_4)
        self.asic_chz_disco.setObjectName("asic_chz_disco")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.asic_chz_disco)
        self.asic_current_limit = QtWidgets.QLineEdit(self.groupBox_4)
        self.asic_current_limit.setObjectName("asic_current_limit")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.asic_current_limit)
        self.verticalLayout_4.addLayout(self.formLayout_5)
        self.gridLayout_3.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.tabWidget.addTab(self.Measurements, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Settings.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(QtWidgets.QApplication.translate("Settings", "Settings", None, -1))
        self.groupBox_6.setTitle(QtWidgets.QApplication.translate("Settings", "General", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Settings", "Working directory", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("Settings", "Mail", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Settings", "Password", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Settings", "Login", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Settings", "Server", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("Settings", "Recipients", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.General), QtWidgets.QApplication.translate("Settings", "General", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("Settings", "Static transfer function", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Settings", "Amplitude", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Settings", "Points", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Settings", "Transfer function", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Settings", "Start frequency exponent", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Settings", "Stop frequency exponent", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Settings", "Frequency points", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Settings", "PSD", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Settings", "Average number", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Settings", "Sampling frequencies", None, -1))
        self.psd_snapshots_count.setInputMask(QtWidgets.QApplication.translate("Settings", "9999", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("Settings", "Asic", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Settings", "X channel discovery", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Settings", "Y channel discovery", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Settings", "Z  channel discovery", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Settings", "Current limit", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Measurements), QtWidgets.QApplication.translate("Settings", "Measurements", None, -1))

